### ISSUE TITLE
no window decoration on gnome

### ISSUE THREAD

**Issue by soloturn** [ii8/havoc#14]
havoc does not have window decorations on gnome, and most likely on weston and others.

**Comment by ii8** [comment]
That is correct, I don't plan to add window decorations.
Often you don't want decorations on your terminal, for example when using a tiling WM, if you do want them you could use another terminal like gnome-terminal.
And adding decorations that are themed correctly would involve adding a dependency on GTK which goes against the goal to keep it minimal.

**Comment by Consolatis** [comment]
Would you be up for accepting a PR which implements the xdg-decoration protocol?
With that protocol (~ 13 lines of code added in its simplest form), havoc can request whatever decoration the compositor prefers (e.g. client -> no decoration or server -> server side ones).

It could also be enhanced to react to a config setting to always prefer server side or no decorations, regardless of what the compositor prefers. If the compositor does not support the xdg-decoration protocol no change in behavior is expected.

**Comment by ii8** [comment]
Sure, don't see why not.

**Comment by Consolatis** [comment]
Alright, will send one a the following days.
Should the PR include the config option so users can switch between no and server-side decorations or always use what the compositor prefers?

**Comment by ii8** [comment]
I don't need the feature or the config option personally, maybe there is some scenario where it's useful for some people? I'm not sure. I think you probably know better than me since it looks like you worked with the protocol a lot recently. I'll merge it either way.
