### ISSUE TITLE
SailfishOS port

### ISSUE THREAD

**Issue by Kabouik** [ii8/havoc#18]
I was trying to package `havoc` for Sailfish OS, and was surprised I could actually build it on SFOS 3.3.0.16 with this (for reference to remember which packages were necessary)

```
git clone https://github.com/ii8/havoc.git
cd havoc
devel-su
zypper install wayland-protocols-devel
zypper install libxkbcommon-devel
zypper install wayland-devel
exit
make CFLAGS="-O2 -DNDEBUG"
devel-su make install
```

I now have the proper binary in `/usr/local/bin`, unfortunately I get this when trying to execute it:

```
[nemo@Sailfish havoc]$ havoc
could not open font file: No such file or directory
using fallback font
your compositor does not support xdg_wm_base, make sure you have the latest version
```

I am not a coder at all, and am not familiar with how compositors work (or even what they are exactly), but SailfishOS does use Wayland. This is the version we have: 1.17.0+git1-1.4.1.jolla.

Is there any hope, or does `havoc` depend on a more recent version? Another SFOS user told me this:
> <Nico[m]> Sailfish doesn't have a concept of maximize, minimize, etc, so wm_base doesn't make much sense. You can probably rip that out and it may work fine

Would that be doable? What should I look for in the sources?

Alternatively, we have some partial Flatpak support on SFOS (just in case you would be planning on a Flatpak release in the future).

**Comment by ii8** [comment]
In wayland there are clients(such as havoc and all the other applications that want to display windows and similar things) and a compositor which is responsible for putting all the windows together onto the screen and sending input events to the clients etc.

`xdg_wm_base` is what's called an interface in Wayland lingo, an agreed way to communicate between client and server. `xdg_wm_base` is a way for a client to ask a compositor to show a `wl_surface` as a window.
https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_surface

It looks like Sailfish OS uses a compositor called "Lipstick", if lipstick does not have `xdg_wm_base` we need some other way to display the terminal window.
I can't seem to find any docs where it says what interfaces are supported.

https://github.com/ii8/havoc/blob/507446c92ed7bf8380a58c5ba2b14aba5cdf412c/main.c#L1263-L1282
This `registry_get` function is called for every interface that the compositor supports, if you add a
```
printf("%s %d\n", i, version);
```
statement in this function(just after line 1265 for example) it will print all the interfaces the compositor supports along with the version.

Then we can look if there is any suitable interface we can use instead of `xdg_wm_base` to display our window.

**Comment by Kabouik** [comment]
Thanks for your very detailed answer, it's greatly appreciated.

Here are the interfaces I could get using your instructions:

```
[nemo@Sailfish havoc]$ havoc
could not open font file: No such file or directory
using fallback font
wl_compositor 3
wl_data_device_manager 1
wl_shm 1
wl_output 2
qt_hardware_integration 1
android_wlegl 2
qt_output_extension 1
qt_surface_extension 2
qt_touch_extension 1
qt_windowmanager 1
wl_seat 2
wl_shell 1
lipstick_recorder_manager 1
alien_manager 1
your compositor does not support xdg_wm_base, make sure you have the latest version
```

**Comment by ii8** [comment]
Fullscreen or not makes no difference to havoc, everything is rendered the same.

It looks like lipstick still uses `wl_shell` which is deprecated in favor of `xdg_wm_base`, so the correct solution here would be to change lipstick.

Alternatively, if that's not an option, I would be happy to have a separate branch where `wl_shell` is used instead of `xdg_wm_base`.
It should be relatively easy to change, calls on xdg wm_base/surface objects need to be changed to their respective wl shell/surface equivalents, and the toplevel and surface configuration code merged into one function. At least that's all it looks like on first glance.

**Comment by ii8** [comment]
Also, don't let what that Nico[m] person said confuse you, it makes no sense and is irrelevant.

**Comment by Kabouik** [comment]
That's an encouraging answer, thanks. A Lipstick upgrade from Jolla (the company that develops SFOS) seems unlikely to me, but I may be wrong. In any case, it's good to hear that you wouldn't mind a second branch for this specific case. I admit I wouldn't really know where to start if I wanted to submit a PR though, despite your instructions.

It might be worth mentioning that, in the end, Lipstick may just be a layer to QtWayland. See this post by one of the original authors: https://github.com/bugaevc/wl-clipboard/issues/85#issuecomment-634799562

**Comment by ii8** [comment]
QtWayland certainly does support the xdg shell, so lipstick just needs to enable it somehow I imagine. This should at least be tried first I think, since it's the correct solution.

My compositor doesn't actually support `wl_shell`(because it's deprecated) so it'll be a bit tricky to implement it. I can try to write it as long as you can do the testing for me.
I could also try to help you and walk you through implementing it yourself if you want.

**Comment by Kabouik** [comment]
Rburchell mentioned that Jolla do not always follow upstream very closely for some packages though, and I don't know where to look to check their version of QtWayland. 

I am of course happy to do the testing for `havoc`, no problem. I would be interested in learning how to implement myself too, but I suspect this would be more time-consuming for you (I have no background in development). 

Side question: is `havoc.cfg` the best place to look to learn more about `havoc` features? I was wondering for instance if it supports true colours, tabs, or tiling (I know it is a minimal terminal, no pressure).

**Comment by ii8** [comment]
I'm stuck at home and have all the time in the world, so it's entirely up to you.

havoc.cfg just has a bunch of configuration options for appearance, what shell to use etc. It's commented so it should all make sense if you read it.
havoc is minimal so there's not a lot of fancy features to talk about, it just does terminal emulation.

**Comment by Kabouik** [comment]
Then we can try a bit of both if you think that's relevant, maybe it wouldn't need to be spoonfed through every step if I can start by following your work, since I don't have much free time at the moment (but I can at least test new commits on the device in evenings).

Yes, `havoc.cfg` is pretty straightforward, that's convenient. What colour support does `havoc` feature? I'm also curious if it can handle `ncurses`' `werase()` function, because I am trying to package a CLI mail client that uses it and we noticed our current native terminal emulator (Fingerterm) refreshing gets wonky when `werase()` is used.

**Comment by ii8** [comment]
Ok, I made a branch called `wl_shell` only took 10 mins anyway, try it I guess, then we can fix any problems together.

havoc can do 24 bit colour and everything else you might want.
`werase` should work, if not, make an issue for it and I'll look into it.

**Comment by Kabouik** [comment]
Awesome! 

Here's what I get:

```
[nemo@Sailfish havoc-wl_shell]$ ./havoc 
could not open font file: No such file or directory
using fallback font
wl_registry@2: error 0: invalid version for global wl_seat (11): have 2, wanted 5
missing required ARGB8888 shm format
```

**Comment by ii8** [comment]
It is.
wl_seat version 5 is what havoc uses, version 2 is what you have.
It may just work if you change the version in the registry_get function where it calls wl_registry_bind for the seat. just change it to 2, see if it works.

Missing ARGB is a problem. That's required by the standard. Maybe it's there but the compositor is not reporting it, so you can just try deleting the test that produces the error.

**Comment by ii8** [comment]
Also, I pushed a small change to the wl_shell branch, I think I missed something earlier. So make sure you pull that.

**Comment by Kabouik** [comment]
Ok, so I did `git pull`, change the version to "2" on L257 of `main.c`, and deleted the two lines corresponding to the ARGB test, compiled again, and now `./havoc` is throwing a segmentation fault (plus the minor missing font warning as it did before).

**Comment by ii8** [comment]
Huh, I guess that really means your compositor does not have ARGB8888 at all.
The only way then is to use whatever other format it has and convert.
There is a shm_format function, in there if you `printf("%d\n", format);` we'll see what formats there are.

**Comment by ii8** [comment]
Unless you added a segfault some other way, if you publish the code, I can check.

**Comment by Kabouik** [comment]
I know nothing about it, but from the looks of it, I'd say that's not very encouraging:

```
[nemo@Sailfish havoc-wl_shell]$ ./havoc 
could not open font file: No such file or directory
using fallback font
0
1
Segmentation fault
```

**Comment by Kabouik** [comment]
```
[nemo@Sailfish havoc-wl_shell]$ git diff main.c
diff --git a/main.c b/main.c
index 2d40a88..eb0d3e5 100644
--- a/main.c
+++ b/main.c
@@ -1235,6 +1235,7 @@ static const struct wl_shell_surface_listener surf_listener = {
 
 static void shm_format(void *data, struct wl_shm *shm, uint32_t format)
 {
+printf("%d\n", format);
        if (format == WL_SHM_FORMAT_ARGB8888)
                term.shm_argb = true;
 }
@@ -1254,7 +1255,7 @@ static void registry_get(void *data, struct wl_registry *r, uint32_t id,
        } else if (strcmp(i, "wl_shell") == 0) {
                term.shell = wl_registry_bind(r, id, &wl_shell_interface, 1);
        } else if (strcmp(i, "wl_seat") == 0) {
-               term.seat = wl_registry_bind(r, id, &wl_seat_interface, 5);
+               term.seat = wl_registry_bind(r, id, &wl_seat_interface, 2);
                wl_seat_add_listener(term.seat, &seat_listener, NULL);
        } else if (strcmp(i, "gtk_primary_selection_device_manager") == 0) {
                term.ps_dm = wl_registry_bind(r, id,
@@ -1545,8 +1546,6 @@ retry:
                               " maybe you should use the xdg_wm_base havoc");
 
        wl_display_roundtrip(term.display);
-       if (term.shm_argb == false)
-               fail(eglobals, "missing required ARGB8888 shm format");
 
        cursor_init();
```

**Comment by ii8** [comment]
Something is wrong, but I don't know what. the 0 means ARGB8888, so not sure why it doesn't work. It looks like the contents of the shm_argb variable are lost.

Is it possible that the execution environment in this Sailfish OS doesn't allow static memory or something?

**Comment by Kabouik** [comment]
I still get the same output after restoring the ARGB check, and the ARGB warning doesn't show anymore so I guess it fails before:

```
[nemo@Sailfish havoc-wl_shell]$ ./havoc 
could not open font file: No such file or directory
using fallback font
0
1
Segmentation fault
```
There probably are some debuggers available but I don't really know where to look. How do I check coredump on regular Linux? SFOS really is Linux (with some pretty outdated stuff as you can see).

**Comment by ii8** [comment]
https://wiki.archlinux.org/index.php/Core_dump
I think sailfish uses systemd. They might be disabled.

**Comment by ii8** [comment]
I don't know if you can get gdb to run on sailfish OS, in that case it would be easier. Just run gdb with havoc and see where it crashes.

**Comment by ii8** [comment]
@Kabouik check irc

**Comment by Kabouik** [comment]
@ii8 Sudden Internet outage, and for some reason none of the phones in the house could get any Internet either. I'm sorry.

So after testing a little more, what I can tell from the current landscape hack under progress is:
- `havoc` does put SFOS in landscape mode when I launch it, or leaves it as it is if it already is in landscape mode; that's a good sign already;
- it has what seems to be a partly correct geometry for landscape: if I take the text orientation as a reference, then window width > height;
- however, the window is would need a CW 90° rotation to fit the actual screen orientation and ratio; right now when I hold my phone in landscape and launch havoc, the OS will stay in landscape but `havoc` is displayed as if I was holding in portrait, and its width overextends beyond the screen height it's height is not enough to fill the screen width.

Not related to this issue, but notes for later:
- I might have spoken too fast regarding the `ncurses`' `werase()` support; might have observed some issues in `cmus` despite no `werase()` in its code as far as I know. Will need to confirm when havoc is fully useable;
- I think it ignores aliases set in `~/.bash_profile`, may ignore all environment variables;
- Holding a key does not repeat it.

**Comment by Kabouik** [comment]
Also, a community member pointed me to a hack he used to force landscape rotation on a game he built for SFOS. We should be able to avoid this for `havoc` since it's pure Wayland and shouldn't require `qxwayland`, but here is what he used:

```bash
qxcompositor_pid()
        {
        # pgrep -u $HOST_USER -f 'qxcompositor --wayland-socket-name ../../display/wayland-1'
        pgrep -f 'qxcompositor --wayland-socket-name ../../display/wayland-1'
        }

{
qxcompositor --wayland-socket-name ../../display/wayland-1 &
export WAYLAND_DISPLAY=../../display/wayland-1
sleep 1
/usr/local/games/supertux2
kill "$(qxcompositor_pid)"
rm /run/user/100000/../../display/wayland-1.lock
}
```

Turns out if I change the binary to launch `havoc` instead of `supertux2`, then the terminal is correctly orientated. Its geometry is wrong, but we know we can swap width and height in `main.c`. 

This is not ideal: it increases the startup time of `havoc`, it conflicts with Flatpak apps already running in SFOS (`havoc` will be superimposed`), and it's qxwayland, but maybe that can give some ideas.

**Comment by Kabouik** [comment]
This is after I swap `height` and `width` back in `main.c`:

![Screenshot_20200529_003](https://user-images.githubusercontent.com/7107523/83209587-3f4dc500-a148-11ea-960c-51717fe42f7d.png)

**Comment by ii8** [comment]
I pushed some changes to the sailfishos branch. It probably won't fix the landscape problem, but it's worth a try.

**Comment by Kabouik** [comment]
Thanks, I just tried it:
- That ones rotates the OS in portrait if it was previously in landscape, leaves it in portrait if it was in portrait;
- `havoc` shows up orientated in portrait;
- its window correctly fills the screen (correct geometry if it was meant to be showing in portrait).

**Comment by ii8** [comment]
Yeah, that all makes sense.
Looks like SailfishOS does not rotate apps like other mobile OSs do. Instead the client app has to do the rotation itself or draw everything on it's side directly.

**Comment by Kabouik** [comment]
Somehow the OS must have a way to rotate itself independently from apps though, because I can also rotate it when no app is maximized (multitask view, app launcher, events view). I can try to ask to SFOS developers later today.

**Comment by Kabouik** [comment]
For reference, this is the stock terminal for SFOS (well, not exactly the same version): https://git.sailfishos.org/mer-core/fingerterm/blob/master/main.cpp

And another one here: https://github.com/direc85/toeterm

This one should work and rotate on SFOS too but I need the SDK to build and try: https://github.com/rburchell/literm

They are all related in some ways.

**Comment by Kabouik** [comment]
There is something weird with the latest commit, check how `cmus` looks like (with and without `tmux`) compared to the first screenshot in landscape above:

![Screenshot_20200529_009](https://user-images.githubusercontent.com/7107523/83290910-f98c0d80-a1d6-11ea-9438-19c3c2cd2167.png)
![Screenshot_20200529_008](https://user-images.githubusercontent.com/7107523/83290913-fabd3a80-a1d6-11ea-8e73-68b487456b4a.png)

Colors and characters used for delimiters are different, even with `tmux`. Or is it just some scaling issue? Also the two screenshots show that there is a redraw issue when `tmux` is not used.

**Comment by ii8** [comment]
Those look like the default colors. It's probably unrelated to the latest commit and just not loading the right havoc.cfg.

**Comment by Kabouik** [comment]
I rebuilt and colours work again, sorry for the noise . I really don't know what happened, but I have been fiddling with ssh for hours and may just have broken something earlier (although I didn't touch to `havoc` binary).

The redraw issue when `tmux` is not used is confirmed though:

![Screenshot_20200529_010](https://user-images.githubusercontent.com/7107523/83292576-de6ecd00-a1d9-11ea-9e55-1aff18dd483c.png)
![Screenshot_20200529_011](https://user-images.githubusercontent.com/7107523/83292581-df9ffa00-a1d9-11ea-85d9-8189180a1c0c.png)

**Comment by Kabouik** [comment]
Alright, did some testing with it.

# Without `tmux`
## `export TERM=xterm-color`
Refreshing looks ok.

##  `export TERM=xterm-256color` (the default every time I run havoc from command line, regardless of my `~/.bash_profile` setting it to `xterm-color`
Refreshing broken.

## `export TERM=linux`
Refreshing looks ok while inside `cmus`, but failure to hide the `cmus` interface when I quit it, I had to `Ctrl+l` to clear the view.

# With `tmux`
`export TERM=xterm-256color`, `export TERM=xterm-color` and `export TERM=linux` all work the same. I guess `tmux` is enforcing some other value that doesn't show when I issue `echo $TERM`.

**Comment by ii8** [comment]
Does havoc print any logs to stderr?

**Comment by Kabouik** [comment]
I edited my message above to add some details.

I just see this when navigating through `cmus` interface:

```
[nemo@Sailfish havoc]$ havoc
unknown DEC Set-Mode 1034
unhandled CSI sequence t
unknown DEC Set-Mode 1006
unknown DEC Set-Mode 1000
unhandled CSI sequence b
unhandled CSI sequence b
unhandled CSI sequence b
unhandled CSI sequence b
```

But that's printed in the SSH terminal from which I ran `havoc`, I'm looking how to check stderr logs.

**Comment by ii8** [comment]
That's it, that's what I wanted, ty.

**Comment by ii8** [comment]
ncurses was using the CSI b sequence to repeat characters, which is why the alignment was wrong. I implemented that in sailfishos branch now, force pull required.

**Comment by Kabouik** [comment]
I can confirm the refreshing issue is not occurring anymore when moving the selection of changing views in `cmus`. I believe it also improved in another ncurses application, `nmail`.

Still some output in stderr:

```
[nemo@Sailfish havoc]$ havoc   
could not open font file: No such file or directory
using fallback font
unknown DEC Set-Mode 1034
unhandled CSI sequence t
unknown DEC Set-Mode 1006
unknown DEC Set-Mode 1000
unknown DEC Reset-Mode 1006
unknown DEC Reset-Mode 1000
unhandled CSI sequence t
unhandled CSI sequence t
unknown DEC Reset-Mode 1000
unknown DEC Reset-Mode 1002
unknown DEC Reset-Mode 1003
unknown DEC Reset-Mode 1006
unknown DEC Reset-Mode 1005
unknown DEC Reset-Mode 1006
unknown DEC Reset-Mode 1000
unknown DEC Reset-Mode 1002
unknown DEC Reset-Mode 1003
unhandled CSI sequence q
unknown DEC Reset-Mode 1006
unknown DEC Reset-Mode 1000
unknown DEC Reset-Mode 1002
unknown DEC Reset-Mode 1003
unknown DEC Set-Mode 7727
unknown DEC Set-Mode 1006
unknown DEC Set-Mode 1000
unknown DEC Reset-Mode 1006
unknown DEC Reset-Mode 1000
unknown DEC Reset-Mode 1000
unknown DEC Reset-Mode 1002
unknown DEC Reset-Mode 1003
unknown DEC Reset-Mode 1006
unknown DEC Reset-Mode 1005
unknown DEC Reset-Mode 7727
unknown DEC Reset-Mode 1004
unhandled CSI sequence t
unhandled CSI sequence t
unknown DEC Set-Mode 1006
unknown DEC Set-Mode 1000
```

And as you can see my `~/.config/havoc/havoc.cfg` with the correct font is being ignored right now, but I'm 97% sure it's human mistake on my side; will look into it.

**Comment by ii8** [comment]
Don't worry about the other missing escape sequences. Terminals are a mess, there's hundreds of non-applicable and pointless things: https://www.xfree86.org/current/ctlseqs.html

**Comment by Kabouik** [comment]
Phew! So just missing landscape and repeat keys (repeat works in other terminals). I haven't received any answer on the #sailfishos Freenode channel so far regarding forcing landscape or enabling autorotation (probably not useful without a touch keyboard).

However, I believe the code you came up with does enforce an orientation regardless of the current OS orientation, which is what we want if we want `havoc` to always show up in one direction only. It's currently enforcing portrait though, and in addition to the OS orientation, we would need `havoc` to rotate its content accordingly. So far, in all commits we tried, the text was always in portrait direction relative to the phone form factor (i.e., regardless of the OS orientation). The only thing that rotated `havoc` content in landscape relative to the phone form factor was the qxcompositor bash hack I posted script above, not ideal.

**Comment by ii8** [comment]
I pushed a change to make pane resizing with arrowkeys work in tmux. But it was unrelated to key repeat, so that needs to be investigated separately.

**Comment by Kabouik** [comment]
I tried on phone before your edit, I confirm the behaviour is unchanged when pressing arrows while holding Ctrl (it just changes focused pane).

**Comment by ii8** [comment]
Nah, I didn't remove anything yet. The commit is probably still correct. I'm not sure, it implements how xterm behaves, but linux console and the vt in tmux behave different.

The resizing doesn't work with the linux console terminal either it seems.

**Comment by Kabouik** [comment]
Does this work on havoc master?

**Comment by ii8** [comment]
no, I added only to sailfishos branch so far

**Comment by ii8** [comment]
For some reason it works if I set $TERM=rxvt or $TERM=linux, but not with xterm or xterm-256color. Even though havoc matches the behavior of xterm, not the others.

**Comment by Kabouik** [comment]
I can confirm the same with the latest commit on device, but when I run havoc, it always ignores my `~/.bash_profile` or prior manual `export TERM=whatever` and run with `xterm-256color`. Other terminals don't do that, is it somehow coded in havoc directly? 

Any disadvantages in using `rxvt` or `linux` despite havoc matching the behavior of xtem only?

**Comment by ii8** [comment]
> Other terminals don't do that, is it somehow coded in havoc directly?

They should, whenever you run a terminal it should set the TERM variable. If you run tmux for example and then `echo $TERM` inside, it should say `screen`.
So exporting TERM before won't work because it will be overridden, you have to set it in the shell after running havoc.
I don't know about bash, you shouldn't really set TERM in there, because you don't know what terminal bash is running in so it could be wrong.

> Any disadvantages in using rxvt or linux despite havoc matching the behavior of xterm only?

Probably, there will be incompatibilities in other places. Terminals are all slightly different, it gets very confusing.

**Comment by ii8** [comment]
Ok, I believe it should work now.

**Comment by ii8** [comment]
I also added an error check for the key repeat timer, so if you look at the logs, maybe it says something useful.

**Comment by Kabouik** [comment]
Huh, that's interesting. None of the native teerminals set $TERM when I launch them. Or as far as I understand they don't override my `~/.bash_profile`. I kinda of suspected setting $TERM there was a bad idea, but in our case it really does solve refreshing/redraw issues in ncurses apps, even in nano. I didn't find any other solution yet unfortunately.

Resizing confirmed to work without changing $TERM in the latest commit, nice!

Regarding repeat keys, is that stderr that I should check? I still see those 
`unknown DEC Reset-Mode xxxx` but nothing printing when I just hold a key in havoc.

**Comment by ii8** [comment]
What's probably happening is that when you run havoc, `~/.bash_profile` is not even executed at all, bash_profile only runs for login shells. The terminals can't override bash_profile, because that runs afterwards. The order is like this:

Run havoc -> havoc sets TERM -> havoc executes bash -> bash executes `~/.bashrc` but not `~/.bash_profile` -> bash prompt appears

or:

Run fingerterm -> fingerterm sets TERM -> fingerterm executes bash as login shell -> bash executes `~/.bash_profile` and `~/.bashrc` -> bash prompt appears

I don't know why it would execute bash as a login shell, normally you don't do that unless it's actually on login, at least on desktop.


And yeah, stderr logs, if there's nothing new there I guess we'll have to check with gdb at some point to find out what's wrong.

**Comment by Kabouik** [comment]
Alright, I removed the manually set variable in my ~/.bash_profile because it is not an ideal workaround for my issues in other terminals anyway, too many risks to break other things. However, what it solves outweighs what it breaks, so instead I set some aliases to temporarily alter TERM for commands that I know don't display correctly with the default TERM value.

I can confirm the other terminals no use their own TERM value, just like havoc was doing already.
I cannot debug in gdb right now, but am happy to do it later tonight or tomorrow. I can try alone to save your time, but I remember you gave me detailed instructions I would never have come up with by myself the last time.

**Comment by ii8** [comment]
I have a few questions:

(1) Which way should havoc rotate for landscape?

(2) Is that always the same? Or might it be different for different phones?

(3) In an ideal scenario would it be good to have both portrait and landscape? Or is portrait completely pointless once you have landscape?

**Comment by Kabouik** [comment]
1. The hardware keyboard is always where the yellow arrow show, so 90° CW rotation would be ideal for havoc. 

# 📲

2. As far as I know, yes. There are few keyboard slider phones and I think they are always orientated that way. There might be exceptions, but unlikely to run Sailfish OS or other related OSes. PostmarketOS and Leste might enable new devices, but that's not ready for use yet and those should be able to install `master` havoc.

3. Portrait is not completely pointless, but wouldn't be a huge advantage unless havoc can show the virtual keyboard. While this would make it useable on all devices, until invoking the SFOS virtual keyboard in havoc is a thing, portrait would only be useful to those who specifically *need* to display CLI monitoring tools in portrait. Just some visual convenience for those who have no keyboard but make some scripts or use an external app to run commands in havoc and use it to show the result/monitor in portrait.

4. Something we didn't think about so far: text selection and scrolling. We can scroll with `tmux` but making it mandatory is not ideal. Native terminals support touch, but I don't know how it's implemented. Konsole (flatpak) supports touch and even emulates taps as mouse input in mouse-enabled tools (like cmus, nnn, etc.), but that might be because it's shipped with more recent protocols that support this?

**Comment by ii8** [comment]
There is an interface for touch events; https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_touch
I wouldn't know what the gestures should be though. Is it just 1 finger to select, 2 fingers to scroll?

I've never done mouse input for cli applications even for the desktop havoc, I find it annoying most of the time when I'm just trying to select and copy-paste. But it's not too hard I think.

**Comment by Kabouik** [comment]
Currently native terminals have a GUI button to toggle gestures between select and scroll modes (plus one mode to show/hide the keyboard but that's probably because they don't use the stock SFOS keyboard, which I think already have this function builtin), and then they use just one finger. I'm not sure if they do that because of a software limitation, or because they didn't want multi-touch gesture. I think it's a pain, actually, so if that would be doable, I would probably prefer one 1 finger for one action, and two (or shift+finger) for the other. I think that would deserve some thinking though.

**Comment by ii8** [comment]
Ok, I did the landscape rendering, turns out it's not actually very hard at all.

**Comment by Kabouik** [comment]
Amazing! Glad it was simpler than expected.

I played with havoc a little more now that I can really interact with it easily, and there's no doubt this is going to be a significant progress compared to the native terminals. Perhaps mostly for those with a hardware keyboard at first, but still i'm sure others could come up with some scripts, desktop files, or use [this](https://openrepos.net/content/coanteen/qcommand) to benefit from the improved havoc output.

**Comment by ingenieroariel** [comment]
Thanks for your work on this! Really hoping to have a similar experience
with NixOS Mobile with Sway when my PinePhone arrives.

Loved witnessing the back and forth over the past few days.

Gracias.

**Comment by Kabouik** [comment]
Short summary:
- Scrolling
- Text selection
- Something is fishy with UTF-8

I was playing with npm and noticed a few wrong characters in some CLI charts or animations. I tested `printf '\xe2\x99\xa5'` in havoc, and it turns out i cannot display it, as opposed to Fingerterm/Toeterm. My locale is set as `en_GB.UTF-8` in environment. Using tmux didn't help.

What surprises me is I'm pretty sure I got accents and other UTF-8 characters working at some point in the past few days, because that was something I was checking when using `cmus` to test havoc builds. Obviously this must be something on my phone because I don't think you changed anything in that regard, but I fail to see what that could be and why other terminals don't pick it the same way.

**Comment by ii8** [comment]
I can display that character fine on desktop. It's likely related to the specific font you are using.

**Comment by Kabouik** [comment]
I'm using DejàVuSans Mono, I just adapted the path to the fond in the config file. However I set my locale to `en_GB.UTF-8` in my `~/.bashrc` instead of the default 'en_GB.utf8`, and now havoc is correctly displaying accented characters. My understanding is both formats should be equally recognized/converted at some basic OS level, but maybe that is missing on SFOS. I created an issue to report it [here](https://together.jolla.com/question/228008/locale-set-to-utf8-not-utf-8-causes-problems-in-some-applications/).

**Comment by Kabouik** [comment]
No that's not it, I lost UTF-8 characters again in another havoc session without changing my LANG nor rebooting. I'll investigate, it's definitely on my end.

**Comment by ii8** [comment]
Hm, the locale might affect whether you are able to input characters using compose, with multiple keystrokes.
It shouldn't change whether `printf '\xe2\x99\xa5'` renders correctly.

**Comment by Kabouik** [comment]
You're right, the character does show up. But somehow `cmus` no longer displays accents, although it did when I posted here 40 min ago.

![Screenshot_20200602_005](https://user-images.githubusercontent.com/7107523/83517007-a7ddce80-a4c7-11ea-84fd-f0f79fab7f31.png)
![Screenshot_20200602_007](https://user-images.githubusercontent.com/7107523/83517008-a8766500-a4c7-11ea-901b-f94a2928eee8.png)

**Comment by Kabouik** [comment]
Just a follow-up of the recent progress:
- Scrolling
- Text selection
- Add in the hardcoded repeat feature ✅
- Something is fishy with UTF-8 ✅
- `.desktop` filefor launcher (I used [that icon](https://www.seekicon.com/free-icon/terminal-icon_2) for my tests, but let me know if you have one you prefer) ✅
- Something is fishy with the font (see braille characters replaced by rectangles in the Node.js apps above, see also lines with viu` image viewer in [havoc](https://user-images.githubusercontent.com/7107523/83685952-f8911c80-a5d8-11ea-8aac-66cc8445f300.png), compared to [literm](https://user-images.githubusercontent.com/7107523/83685955-f929b300-a5d8-11ea-9eb9-376cba91ed14.png)
- You explained to me that ` ~/.bashrc` will only set things in bash sessions, not globally, and havoc started from desktop launcher apparently can't see it. Isn't it going to be an issue for custom `$PATH` and other user-defined settings?

I'm sorry, this is by far the longest issue you have had here, but I find the progress the last few days truly exciting.

**Comment by Kabouik** [comment]
I think only `havoc.spec` below needs some changes, the rest should be ready for OBS.

`havoc.spec` 
```
Name:          Havoc
Version:       85fdde7
Release:       1
Summary:       A minimal terminal emulator for Wayland on Linux
Group:         System
Vendor:        Murray Calavera <murray.calavera@protonmail.com>
Distribution:  Sailfish OS
Packager:      Kabouik <matf[redactedforbots]disr.it>
Source0:  	   %{name}-%{version}.tar.gz
URL:           https://github.com/ii8/havoc

License:       MIT

%description
Havoc is a minimal but modern terminal emulator for Wayland. It supports everything you would expect from a terminal emulator on a PC, including 24bit colours and TUI features that Fingerterm and, to a lower extent, Toeterm, cannot handle. Havoc being developed for PC originally, it is meant to be used in landscape with a hardware keyboard.

You can still use Havoc with no hardware keyboard, using qCommand, any other terminal, or .desktop files to print command outputs that do not render correctly in other terminals. To issue a command in Havoc from another application, use "havoc -l COMMAND", where "-l" is to hold in case the output does not keep a process running.

# Features
- 24bit colours
- Full support for ncurses features and other TUI
- Easy multi-touch text selection; no more conflict between selecting and scrolling
- One finger scrolling (like all native SFOS apps except terminals
- User configuration in ~/.config/havoc.cfg by default (font, font size, colours, opacity of the cover, etc.)
- Support for compose and dead keys if your hardware keyboard is set to use a xkb layout with those (additional package)

# Disclaimer
I am not the developer of Havoc, I just packaged it for SFOS. Havoc is being actively developed by Murray Calavera (ii8).

%license
LICENSE

%build
make CFLAGS="-O2 -DNDEBUG"

%install
make PREFIX=/usr DESTDIR=%{?buildroot} install

%config
/home/nemo/.config/havoc.cfg

%post
# Change permissions on the config file
chmod -R 755 /home/nemo/.config/havoc.cfg
chown -R nemo:nemo /home/nemo/.config/havoc.cfg

%postun

%changelog
* Sat Un 06 2020 Kabouik <matf[redactedforbots]disr.it> 85fdde7
- First SFOS package based on the 85fdde7 version.
```

Please keep in mind I'm not in software development at all, I don't want to mistakenly take any credit for Havoc. I put myself as packager here because I will keep using SFOS in any foreseeable future, but feel free to scrap me from the file if you want to upload on the repository yourself.

`_service`
```
<services>
  <service name="webhook">
  <param name="repourl">https://github.com/ii8/havoc.git</param>
  <param name="branch">sailfishos</param>
  </service>
<service name="tar_git">
  <param name="url">https://github.com/ii8/havoc.git</param>
  <param name="branch">sailfishos</param>
  <param name="revision">85fdde75d98d4468dceabeb81253b834c6390a82</param>
  <param name="token"/>
  <param name="debian">N</param>
  <param name="dumb">N</param>
</service></services>
```

`/usr/share/applications/havoc.desktop`
```
[Desktop Entry]
Type=Application
Name=Havoc
Exec=havoc bash -l
Icon=havoc
```

`/home/nemo/.config/havoc.cfg/`
```
[child]
# program to run in child process
program=bash

[window]
# opacity of background from 0 (fully transparent) to 255 (fully opaque)
opacity=210

# render a margin to exactly match window size hints from the compositor
margin=yes

[terminal]
# size of terminal
rows=16
columns=140

# number of lines to keep in scrollback
scrollback=1000

[font]
# heigth of a single glyph in pixels
size=30

# absolute path to a truetype font
path=/usr/share/fonts/dejavu/DejaVuSansMono.ttf

[colors]
# Railcasts dark by Chris Kempson
foreground = #e6e1dc
background = #060a07

# black
color0  = #060a07
color8  = #5a647e

# red
color1  = #da4939
color9  = #da6b5f

# green
color2  = #a5c261
color10 = #abc277

# yellow
color3  = #ffc66d
color11 = #ffd99e

# blue
color4  = #6d9cbe
color12 = #94acbe

# magenta
color5  = #b6b3eb
color13 = #d2d0eb

# cyan
color6  = #519f50
color14 = #6a9f69

# white
color7  = #e6e1dc
color15 = #f9f4eb
```

And the icon should go into `/usr/share/icons/hicolor/86x86/apps/havoc.png` (there are folders for .svg and higher resolutions rasters too but the icon was not used when I tried there).

**Comment by ii8** [comment]
We're done here. Very nice. :champagne:
Port is at: https://github.com/Kabouik/havoc
In the repo: https://openrepos.net/content/kabouik/havoc

The font issue, unicode block elements not fully filling cells, is separate(and very difficult to fix it seems).

**Comment by Kabouik** [comment]
Thanks for your continued support and patience, it was greatly appreciated and I'm sure other SFOS users will benefit from the port.

**Comment by Kabouik** [comment]
Just a quick message to show you that the SailfishOS port didn't bring thousands of new users of course, but it seems Havoc has a steady download slope and is being used everywhere. I suspect that people who download it own a keyboard phone, and in that case there is no real competition for Havoc so they likely do use it, instead of download it just to uninstall it afterwards.

![Screenshot_2020-11-12 Download Details Havoc OpenRepos net — Community Repository System](https://user-images.githubusercontent.com/7107523/98945414-6461a480-24ea-11eb-8cff-e76f8a2da8eb.png)
