### ISSUE TITLE
Mouse cursor isn't drawn in the window.

### ISSUE THREAD

**Issue by PaperMountainStudio** [ii8/havoc#21]
Using the latest master, the mouse cursor isn't drawn when it is inside the havoc window. I am on Void Linux, using Sway 1.4. It worked properly before commit 8b9a4aea78e28046fb29b2314458b350f6cb3762.

I found this new error appearing which I can not reproduce on a build before the commit mentioned above:
```
unknown parameter to CSI-J: 3
```

**Comment by ii8** [comment]
That CSI J 3 sequence is supposed to clear the scrollback, it's unrelated, just not implemented.

Before that commit, havoc never drew a cursor, the cursor image was just whatever was left over from the last program that rendered a cursor so it could be anything.

Now we use libwayland-cursor to render the cursor which looks in standard locations for the cursor theme.
The cursor theme can be set in:
`~/.icons/default/index.theme`
`~/.local/share/icons/index.theme` (according to arch wiki, haven't tested this one myself)
`XCURSOR_THEME` environment variable.

So set up the theme in one of those, my `.icons/default/index.theme` looks like this for example:
```
[Icon Theme]
Name=Default
Inherits=Breeze_Snow
```
and I have the Breeze_Snow theme in /usr/share/icons installed with xbps.

This will affect other programs as well of course.

**Comment by PaperMountainStudio** [comment]
Apparently this is the solution, although I don't like that havoc doesn't draw a cursor when a theme is not specified, but I guess this is an libwayland-cursor issue. Thanks a lot for your time :+1:

**Comment by wildart** [comment]
You can link from Breeze theme the missing `text` cursor file in your default theme, but it would be nice to use the default cursor if the particular one is not available.
