### ISSUE TITLE
Do a release once in a while

### ISSUE THREAD

**Issue by PaperMountainStudio** [ii8/havoc#22]
I have a working Void package template, but Void packages only software with releases, they do not accept commit snapshots. Could you tag a release once in a while?

**Comment by ii8** [comment]
Yeah, will do. I'm making some changes at the moment, so I'm gonna test those for a bit and then maybe do a 1.0

**Comment by ii8** [comment]
I kind of wanted to do #13 before releasing, but it's a lot of work for relatively little benefit so w/e.

**Comment by PaperMountainStudio** [comment]
Nice, you can take your time, it isn't really an urgent thing.

**Comment by ii8** [comment]
[made one](/ii8/havoc/releases/tag/0.1.0). better to do a release now before changing everything because it will become more unstable

**Comment by PaperMountainStudio** [comment]
thanks :slightly_smiling_face:  https://github.com/void-linux/void-packages/pull/22708
