### ISSUE TITLE
Can not build; no rule for xdg-shell.c

### ISSUE THREAD

**Issue by L-as** [ii8/havoc#23]
I get this error: `make: *** No rule to make target 'xdg-shell.c', needed by 'xdg-shell.o'.  Stop.`

I am getting my dependencies from nixpkgs, but building manually.

Any ideas?

**Comment by ii8** [comment]
Do you have the wayland-protocols package?

What does `pkg-config --variable=datarootdir wayland-protocols` output?

**Comment by L-as** [comment]
Oh, I didn't realize you need pkg-config, thanks!
