### ISSUE TITLE
Add scrollback keyboard shortcut

### ISSUE THREAD

**Issue by PaperMountainStudio** [ii8/havoc#24]
possible default configuration (but it should be configurable):
- `Shift+ArrowUp/Down` should scroll one line
- `Shift+PageUp/Down` should scroll one screen

Thanks :)

**Comment by ii8** [comment]
I'm thinking about this already. I also want to add a way to scroll all the way to the bottom, reset the terminal etc.

The question is how keybind configuration should be done. Should mouse buttons be included, so you could do `Shift+Mouse1` for example. In which case, should the scroll wheel be configurable as well, so it's not hardcoded to scrolling anymore but rather configurable. Further, what about starting a selection? Should left mouse button to start a selection be configurable as well?
I'm not sure where to draw the line between hardcoded and configurable for input actions.

**Comment by PaperMountainStudio** [comment]
Scrolling all the way to the bottom is done usually by typing a character when in a scroll mode. It will reset the scroll position to bottom. I am not really interested in binding mouse actions, the current default is fine for me.

**Comment by ii8** [comment]
> Scrolling all the way to the bottom is done usually by typing a character when in a scroll mode

Yes, but this is super annoying imo. Sometimes while looking at something further up in the scrollback you want to type without it jumping down again.

**Comment by PaperMountainStudio** [comment]
ok, I can get used to a different style of scrolling to bottom 👍

**Comment by ii8** [comment]
This is done now.
