### ISSUE TITLE
ability to set app_id

### ISSUE THREAD

**Issue by sijad** [ii8/havoc#28]
it'd be useful to be able to set the `app_id` via options.

I use `app_id` to set [options](https://github.com/sijad/dotfiles/blob/e1072a31910acfefee49f15b0afefc8953eb5ec7/.config/sway/config#L66) to specific `app_id`.

**Comment by sijad** [comment]
I send an PR, if you think this can be useful

**Comment by ii8** [comment]
Yeah, that makes sense. I would merge that.
Does it need to be configurable though? I think you can just hardcode it to "havoc".

**Comment by sijad** [comment]
I'm not sure what do you mean by hardcodding it? you mean I have to have two havoc? one of them with hard codded `job_id`?

**Comment by ii8** [comment]
Hardcoding just means it's not configurable via the command line options or havoc.cfg, it's just always set to "havoc".
No, just one havoc.

Look in xdg-shell.h, it can be set with just one function call.

**Comment by sijad** [comment]
In that case I have to have multiple instance of installed havoc. you can set `app_id` in termite using `--name` option.

and I'm not sure have that in config file would be useful either.

this is my changes: https://github.com/sijad/havoc/tree/app-id

**Comment by ii8** [comment]
Oh, I see, you want to distinguish havoc instances.
Ok sure, have a command line option for it.
But it should default to "havoc".
