### ISSUE TITLE
Unable to run havoc

### ISSUE THREAD

**Issue by onny** [ii8/havoc#3]
```
./havoc 
wl_registry@2: error 0: invalid version for global wl_seat (5): have 4, wanted 5
missing required formats
Clean exit
```
I guess its incompatibel to my Wayland version?
Best regards,
Jonas

**Comment by ii8** [comment]
That is the version of the interface that your compositor advertises.
If you are using weston, you will need 1.12 or greater I believe.
I have it working with 1.12.90

You can check the interfaces of your compositor using `weston-info` if you have it.
It needs to show at least `zxdg_shell_v6, version: 1` and `wl_seat, version: 5`
You may be able to simply reduce the wl_seat version here: https://github.com/ii8/havoc/blob/master/main.c#L586
But zxdg_shell_v6 is required.

**Comment by Jammizzle** [comment]
derp
