### ISSUE TITLE
havoc with no command line option and multiple program args does nothing

### ISSUE THREAD

**Issue by sijad** [ii8/havoc#30]
havoc with a program and multiple args exit immediately and does nothing. 

how to reproduce:

```bash
havoc echo ok # does nothing and exit with code 0
havoc echo # works as intended
havoc -l echo ok # works as intended
```

seems to be related to `forkpty` but I couldn't debug.

**Comment by ii8** [comment]
Doesn't look like there's a problem. This is the expected behavior. Havoc closes when the child program exits, if you want it to stay open to look at output, that's what `-l` is for.
