### ISSUE TITLE
Global config file

### ISSUE THREAD

**Issue by xWNgLWT0mQf** [ii8/havoc#31]
Good day. I was wondering if it would be possible for a master config file supported by this project? For instance, have a config file loaded at /etc/havoc/havoc.cfg. I would be willing to write the code and open a pull request for this change, but I wanted your opinion before I do that.
My thought is that the config's priority would be thus: $XDG_CONFIG_HOME first, then in $HOME/.config, then in /etc/havoc and last in the current working directory.
The reason for this request is that (some) package management systems only install files listed in the Makefile, whick would prevent endusers from getting a config file by default.

**Comment by ii8** [comment]
See https://github.com/ii8/havoc/issues/25

**Comment by xWNgLWT0mQf** [comment]
I see. My apologies for not looking through the old issues. Is it possible to have the config file copied to usr/share/example (as suggested in #25) by the makefile?

**Comment by ii8** [comment]
Unfortunately I don't think `/usr/share/example` is standard, a lot of distributions don't have this, so it should be done by the package script instead(if it makes sense for that distro).

**Comment by xWNgLWT0mQf** [comment]
Very well. I understand your reasoning. Please feel free to close this issue.
