### ISSUE TITLE
scrolling many lines at once (ie inside vim/neovim) is very, very slow in comparison to st

### ISSUE THREAD

**Issue by matu3ba** [ii8/havoc#38]
[st](https://st.suckless.org/) ie accessible with `git clone https://git.suckless.org/st`

**Comment by ii8** [comment]
Hm, scrolling text files in vim is perfectly smooth for me. Could you give more details? Does the text contain a lot of utf8 characters? Are you making sure the terminal size is the same to make the comparison fair etc.

**Comment by matu3ba** [comment]
I will look into this again tomorrow. As I vaguely remember, the problem appeared on a bunch of terminal color codes.

**Comment by matu3ba** [comment]
I cant reproduce it right now, so I close this for now.
