### ISSUE TITLE
terminal codes for adjusting screen by vim dont work

### ISSUE THREAD

**Issue by matu3ba** [ii8/havoc#39]
On 1a5a6ce5256293631e4caf07cd498c68028df6c5 see the righthand side

Starting vim

![starting_vim](https://user-images.githubusercontent.com/13089667/145982770-e5169dfa-5ce3-489f-b4ef-8cba0dc5c215.png)

After quitting vim

![vim_terminal_codes](https://user-images.githubusercontent.com/13089667/145982275-d414e419-0edf-492c-9ccc-8956816bf159.png)

Bottom left you see the according console output, which shows unhandled control sequences. 
Not sure, which ones you want to implement cause there are a big pile of them.

Neovim however works fine.

**Comment by ii8** [comment]
So libtsm did a soft reset when it got a DECRQM csi which would reset the alternate screen flag thus causing this problem.
I have no idea why this reset was done but xterm doesn't do it so we won't either and I've removed it from libtsm.

**Comment by ii8** [comment]
b38c4ec1d3355bafc825e80476fac666f4f5748a

**Comment by matu3ba** [comment]
works now. thanks.
