### ISSUE TITLE
How to change font transparency?

### ISSUE THREAD

**Issue by Unesty** [ii8/havoc#4]

**Comment by ii8** [comment]
The font is always fully opaque at the moment.

**Comment by ii8** [comment]
I just thought about this again.

Font transparency would require extra code for alpha blending in the critical section of the drawing loop.

In havoc I can make the background transparent but leave the font fully opaque. If I want the font to be partially transparent along with the background, often the compositor can do that instead (usually in hardware).

The remaining case is where I want the font to be more transparent than the background, but I'm not sure this would ever be useful or desirable.

Why did you want this feature?

**Comment by Unesty** [comment]
I want to see through symbols. Using compositor to change transparency is easier than changing config or source code.
