### ISSUE TITLE
arch linux pacman progress bars offset one line

### ISSUE THREAD

**Issue by jmcamp** [ii8/havoc#40]
I'm running havoc git on sway on arch linux.

When I execute pacman commands such as "sudo pacman -Syy" in havoc, the progress bars are displayed offset one line:
![havoc_pacman](https://user-images.githubusercontent.com/12588649/148612937-04f42a32-18d2-418a-94ef-d26c52f7ef00.png)

If I run the same command in sakura, they are displayed correctly:
![sakura_pacman](https://user-images.githubusercontent.com/12588649/148612992-d8eb4e3e-d462-4c71-ae4b-d963ea3bbcd3.png)

Havoc outputs the following when running "sudo pacman -Syy":
unhandled CSI sequence F
unhandled CSI sequence E
unhandled CSI sequence F
unhandled CSI sequence E
unhandled CSI sequence F
unhandled CSI sequence E

**Comment by ii8** [comment]
Those missing CSI sequences were indeed the issue, should be fixed in 1de025a7e75318c2319fda209faf0bd42e7f1e1a
