### ISSUE TITLE
Havoc not support vim's ttymouse to resize vim's window and move focus by tap on vim..

### ISSUE THREAD

**Issue by ahmadraniri1994** [ii8/havoc#42]
I used to set Vim's ttymouse=sgr or other values so I can easily resize Vim's window or move focus by tap to other windows (I use mouse or touchpad), but it doesn't work with havoc (it's not like other Wayland terminal,  foot, mlterm, wayst). Any clue to fix that? Thanks.

**Comment by ii8** [comment]
Havoc does not send any mouse codes currently. The only implemented mouse features are selection and copy/paste.

**Comment by ahmadraniri1994** [comment]
Oh, thanks. Closing it now.
