### ISSUE TITLE
Can't copy and paste between havoc and qt applications

### ISSUE THREAD

**Issue by ahmadraniri1994** [ii8/havoc#43]
I just realized that I can't copy and paste between havoc and qt apps. Like, when I copy text from havoc and then I try to paste to qt apps, the text isn't copied. Or when I copy text from qt apps and paste to havoc, the text isn't copied.

**Comment by ahmadraniri1994** [comment]
Kind of **solved** with help of external tools (`wl-paste and clipman`), I need to run `wl-paste -t text --watch clipman store` . I will keep this issue open. Now I can share clipboard between `havoc` and `qt apps` or vice versa. Thanks.

**Comment by ii8** [comment]
This should work without using external tools now since 5cac85188f4ab63f2f42d0e5a2021625292ad00d

**Comment by ahmadraniri1994** [comment]
Thanks @ii8 , it works.
