### ISSUE TITLE
Havoc won't display system cursor.

### ISSUE THREAD

**Issue by realFenix7** [ii8/havoc#44]
At first I thought this was a problem with my system (as in I didn't have any cursor theme installed), then I installed one (Vanilla-DMZ) but the problem was still happening and it only occurs while hovering over Havoc, after leaving the cursor it returns to normal.

If this is intentional, please allow a way to configure this on havoc.cfg as it confuses me while I am on my workflow. By the way, this project is amazing and I am very happy to use it! 

Relevant information:
OS: FreeBSD
Compositor: Sway
Compiled using the ports system from FreeBSD.

**Comment by ii8** [comment]
I'm glad you like it!

How did you install the cursor theme?
I don't have FreeBSD so I'm now sure how much I'll be able to help, but what's important is that the libwayland-cursor library knows about the cursor theme.

Also see #21

**Comment by realFenix7** [comment]
Hello again! This seems to indeed fix my problem (partially) as it works with some cursors themes (I've tried two, Adwaita and redglass), Adwaita successfully works but redglass does not. I think it's due to redglass not having an I-Beam cursor icon.

I think the default should be to use the normal cursor icon when I-Beam is not provided. Also I've installed all of the cursor icons using `pkg`, package manager for FreeBSD.

**Comment by ii8** [comment]
Hm, using the default cursor doesn't help when there is no theme configured, idk why libwayland-cursor just doesn't give anything when things aren't configured perfectly. It seems a bit dumb for havoc to ship it's own fallback cursor. I'll have to figure out what the proper solution is here.

**Comment by realFenix7** [comment]
It might be useful to create an issue in libwayland-cursor, this should not be intended behavior at all. It is probably a bug.

**Comment by ii8** [comment]
Try it with 3a1c9716709919026e7f5763450dae25d069d25e

The problem was that some cursor themes, including the fallback theme from libwayland-cursor, have different non-standard names for the cursors. This should fix redglass as well I think.

**Comment by realFenix7** [comment]
Seems to work perfectly with the new commit! Here's a screenshot of Havoc with neovim open:
![20230201_23h02m54s_grim](https://user-images.githubusercontent.com/123918973/216213037-56ac6950-5206-421e-9ede-e418da879965.png)

I will be closing this issue now. Thank you very much!

**Comment by Consolatis** [comment]
> The problem was that some cursor themes, including the fallback theme from libwayland-cursor, have different non-standard names for the cursors. This should fix redglass as well I think.

See https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3651 for a generic fix in wlroots regarding the same issue.

So if somebody wants to fix this upstream: the same / similar changes could be applied to [libwayland](https://gitlab.freedesktop.org/wayland/wayland) but I currently have too much stuff on my plate to do it myself.
