### ISSUE TITLE
Open with executing scripts

### ISSUE THREAD

**Issue by debeetle** [ii8/havoc#52]
Thanks for this marvellous job!

I use terminal everywhere in my daily workflow. And the most thing that I do is opening a terminal with interactive scripts. However when it came to havoc, I found no option such as `-e` like other terminals to meet my needs. So is there any possibble workaround to achive this goal? Any advise will be appreciated!

**Comment by ii8** [comment]
Hello, I'm not sure what exactly you want to do, but here are some example commands to try:

```sh
havoc -l havoc -h
havoc -l ls
havoc -l sh my-cool-script.sh
havoc sh -c 'echo hi; sleep 3'
havoc -l lua -e 'print("hi")'
```

**Comment by debeetle** [comment]
Thanks for replying! I found that havoc needs no option to execute a command, and your advise is helpful. I will close this issue
