### ISSUE TITLE
CJK font support

### ISSUE THREAD

**Issue by debeetle** [ii8/havoc#53]
Hi again!
I found CJK font cannot show correctly in this minimal terminal, is there possible to add this feature? Any advice will be appreciated.

**Comment by ii8** [comment]
Havoc supports double width characters, but it has to be a monospace font, which font is causing problems?

**Comment by debeetle** [comment]
Thank you for your time. It's WenQuanYi Zen Hei, a widely-used CJK font. And it's not a mono font, so I guess it's the problem. Changing the font to WenQuanYi Zen Hei Mono in /etc/fonts/local.conf and relogining does not work. Am I making some mistakes?

**Comment by debeetle** [comment]
In cfg file I set ubuntu mono which does not support cjk. I thought havoc would automatically roll back to local cjk font settings without specifying . And it seems that there can only exist one font in config. Is it possible to set a font for english while another for cjk? 
Thanks for replying!

**Comment by ii8** [comment]
You can't set multiple fonts at the moment, that's a feature that could be added alongside specifying a separate font for bold text.
Or for now you could use fontforge to merge the two fonts into one.

**Comment by debeetle** [comment]
That's helpful, I'll close this issue
