### ISSUE TITLE
Doesn't render nerd fonts

### ISSUE THREAD

**Issue by derdilla** [ii8/havoc#55]
Consider this screenshot:

![image](https://github.com/user-attachments/assets/f3e96874-a4cc-4437-9f56-44865c517aa5)

The top terminal is alacrity the bottom one is havoc, both showing the yazi file manager TUI. I think those missing icons from are from [nerdfonts](https://www.nerdfonts.com/).

I understand that havoc is a minimal terminal and I don't want to pollute it with my weird edge-case faetures, but I read in another issue that it should support those characters and wanted to bring it to your attention in case this is a bug/regression.

**Comment by ii8** [comment]
All monospace glyphs contained in the ttf font file specified in havoc.cfg should be rendered.
Havoc doesn't go looking for other font files if a glyph is missing. So to know if there's a problem I'd have to know if those icons are actually in the font file you're using, or if alacritty is pulling them from somewhere else using and advanced font manager like fontconfig.

I'm not really against allowing multiple font files to be configured, so a fallback font can be used if glyphs are missing in the main font. I don't want to add fontconfig though, that's a huge dependency and not suitable for minimal systems.

**Comment by derdilla** [comment]
Thanks allot for the response that cleared some things up! I traced through the fonts alacritty uses for yazi (CaskaydiaCoveNerdFont-Regular) and now no longer get any apparent misses.

I assume those cut of symbols are already tracked in #16?
![image](https://github.com/user-attachments/assets/64d3d991-de71-4cfd-a8f4-513c413f5ec4)

As I no longer need fallback fonts feel free to close this :)
