### ISSUE TITLE
Support make --prefix=... and make DESTDIR=... ?

### ISSUE THREAD

**Issue by kindaro** [ii8/havoc#7]
Thank you for your great work on this program! I can give a testament that it works great, and _fast_.

I was trying to package it for my operating system _(that would be Arch Linux)_ and it appears to me that there is no support for building into a temporary location.

1. The usual way to set the location from which a program will be run is to issue `./configure --prefix ...`, as described, for instance, [here][1]. But there is no `configure` script and `make` does not understand this parameter either.
2. The usual way to build into a temporary location is to issue `make DESTDIR=... install`, as described, for instance, [here][2]. But it appears to me that this option is ignored.

[1]: https://www.gnu.org/software/make/manual/html_node/Directory-Variables.html
[2]: https://www.gnu.org/prep/standards/html_node/DESTDIR.html

Now, I was able to build the program into a temporary location by editing `Makefile` by hand and changing the value of  `PREFIX`, but I would not like to use `sed` to correct this value every time I want to update my package.

If you could arrange it so that `make install` understands `DESTDIR` and that `make` understands `prefix`, I am sure many people will be able to enjoy the fruits of your work with greater ease.

**Comment by ii8** [comment]
Hello, I'm glad you like it. In make you can actually set any of the variables on the command line, see [here](https://www.gnu.org/software/make/manual/make.html#Overriding)

And DESTDIR is now respected in the makefile, so you can write:
```
make DESTDIR=... PREFIX=... install
```

**Comment by kindaro** [comment]
Great! [Now there is a package in Arch User Repository.][1]

[1]: https://aur.archlinux.org/packages/havoc-git
