### ISSUE TITLE
Use the shell of the current user's preference by default?

### ISSUE THREAD

**Issue by kindaro** [ii8/havoc#8]
I see that by default `/bin/sh` is used. Perhaps it would be more reasonable to use whichever shell is specified for the current user in `/etc/passwd`, or otherwise preferred? For instance, `SHELL` environment variable is a standard location where the path to the user's preferred shell executable may be found. That would make the experience so much better from the start.

To safeguard from non-existent or non-executable `SHELL`, a fallback to `/bin/sh` may still be put in place.

**Comment by ii8** [comment]
I realise that most other terminals use /etc/passwd and SHELL env variable, but I don't really see the point. You can already set it in the config file and on the command line.
If somebody wants this enough to implement it, feel free. But I don't really care about having 4 different places to configure the shell.
