### ISSUE TITLE
How to use clipboard?

### ISSUE THREAD

**Issue by kindaro** [ii8/havoc#9]
Selected text does transfer to `PRIMARY` buffer, and from there can be pasted, for instance, with middle mouse click or triple tap. But I wonder if there is a way to use the `CLIPBOARD` buffer. Most applications favour it anyway, and there is even a [conversation][1] in the direction of limiting and eventually dropping the `PRIMARY` support.

[1]: https://wiki.gnome.org/Initiatives/Wayland/PrimarySelection

It is generally considered that Ctrl+Shift+C may be used to copy and Ctrl+Shift+V to paste from the `CLIPBOARD` buffer. Such key bindings would not overshadow any terminal input.

**Comment by ii8** [comment]
That is not implemented at the moment, only primary selection is.

**Comment by ii8** [comment]
Copy-pasting to/from `CLIPBOARD` is possible now with Ctrl-Shift-c and Ctrl-Shift-v, 7ef9ad227538a3034adacdb20f9d0559e5145008.
I plan to make keybindings properly configurable before the next release.

**Comment by ahmadraniri1994** [comment]
Hello, sorry to bother you, I can't paste to havoc when copying text from outside havoc (e.g, browser), I use default keybinding.

**Comment by ii8** [comment]
@ahmadraniri1994 I've addressed this comment in #43
